version: '3'

services:
  django:
    labels:
      - "traefik.http.routers.websocket.rule=Host(`back.t99ltd.info) && Path(`/ws/color/`)"
      - "traefik.http.services.websocket.loadbalancer.server.port=8000"
      - "traefik.http.services.websocket.loadbalancer.sticky=true"
      - "traefik.http.routers.websocket.entrypoints=websecure"
      - "traefik.http.routers.websocket.tls=true"
      - "traefik.http.routers.websocket.tls.certresolver=myresolver"
